services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-supersecurepassword}
      POSTGRES_DB: ${PG_DBNAME:-reception}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  atlas:
    image: arigaio/atlas:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      - migrate
      - apply
      - --url
      - postgres://${PG_USER:-postgres}:${PG_PASSWORD:-supersecurepassword}@db:5432/${PG_DBNAME:-reception}?sslmode=disable
      - --dir
      - file:///migrations

  bot:
    image: ghcr.io/gxjakkap/reception:main
    restart: always
    pull_policy: always
    env_file:
      - .env
    environment:
      - PG_HOST=db
    depends_on:
      atlas:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

volumes:
  db_data:
